// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPoJx7G12D3oQpmQlCR4o4h-wLzNsX030',
    appId: '1:1061200140405:web:5d80d6fd6ffd3d78fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    authDomain: 'flutterprojefcts.firebaseapp.com',
    storageBucket: 'flutterprojefcts.appspot.com',
    measurementId: 'G-4JV37JVPV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUMHgzJVcDSGOpygrV19hp-MmU_xfbklQ',
    appId: '1:1061200140405:android:d2925b1af4d4bf37fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbHMsMrYCUHDq-NozklWQJib3OMs0I2Z8',
    appId: '1:1061200140405:ios:119bc908863a2605fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
    iosBundleId: 'com.example.myShoppingAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbHMsMrYCUHDq-NozklWQJib3OMs0I2Z8',
    appId: '1:1061200140405:ios:119bc908863a2605fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    storageBucket: 'flutterprojefcts.appspot.com',
    iosBundleId: 'com.example.myShoppingAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPoJx7G12D3oQpmQlCR4o4h-wLzNsX030',
    appId: '1:1061200140405:web:00977b78e928c3d7fd403c',
    messagingSenderId: '1061200140405',
    projectId: 'flutterprojefcts',
    authDomain: 'flutterprojefcts.firebaseapp.com',
    storageBucket: 'flutterprojefcts.appspot.com',
    measurementId: 'G-WZW7ZFBZ8K',
  );
}
